import type { SubjectId } from '@/constants/subjects';
import type { DiagramKind, ToolKind } from '@/constants/tools';

export interface ImageAttachment {
  id: string;
  /** Local file (native) or data URI (web) of the compressed image sent to DeepSeek. */
  uri: string;
  /** Small JPEG data URI for rendering inside the transcript WebView. */
  thumb: string;
  width: number;
  height: number;
}

export interface UserMessage {
  id: string;
  role: 'user';
  text: string;
  createdAt: number;
  images?: ImageAttachment[];
  tool?: {
    kind: ToolKind;
    diagram?: DiagramKind;
    topic: string;
    /** Hidden source material for the tool (lecture notes, missed questions); not shown in the bubble. */
    context?: string;
  };
}

export type MessageStatus = 'streaming' | 'done' | 'error' | 'stopped';

/** Tokens billed by the API, summed over requests. */
export interface TokenUsage {
  requests: number;
  /** All input tokens, including those served from DeepSeek's context cache. */
  promptTokens: number;
  cacheHitTokens: number;
  /** All output tokens, including reasoning. */
  completionTokens: number;
  reasoningTokens: number;
}

/** Usage keyed by the model id that was requested (prices are per model). */
export type UsageByModel = Record<string, TokenUsage>;

export interface AssistantMessage {
  id: string;
  role: 'assistant';
  createdAt: number;
  /** Markdown answer (or a short summary of the artifact for tool replies). */
  content: string;
  /** Thinking-mode chain of thought (`reasoning_content`). */
  reasoning?: string;
  status: MessageStatus;
  error?: string;
  /** DeepSeekError kind, so the UI can offer "Open Settings" vs "Retry". */
  errorKind?: string;
  /** Transient status while a tool artifact is being generated, e.g. "Writing question 3…". */
  progress?: string;
  model?: string;
  thinking?: boolean;
  thinkingMs?: number;
  finishReason?: string | null;
  tool?: ToolKind;
  artifact?: Artifact;
}

export type Message = UserMessage | AssistantMessage;

export interface Chat {
  id: string;
  title: string;
  subject: SubjectId;
  createdAt: number;
  updatedAt: number;
  messages: Message[];
  /** True once the title was generated by DeepSeek or set by the user. */
  titleLocked?: boolean;
  /** Every request made for this chat, including regenerated replies, answer checks and the title. */
  usage?: UsageByModel;
}

/* ---------- Tool artifacts ---------- */

export interface MultipleChoiceQuestion {
  question: string;
  choices: string[];
  answerIndex: number;
  explanation: string;
  hint?: string;
  /** An independent re-solve disagreed with this answer key, so the student should double-check it. */
  unverified?: boolean;
}

export interface PracticeQuestion extends MultipleChoiceQuestion {
  topic: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

export interface PracticeTest {
  title: string;
  topic: string;
  questions: MultipleChoiceQuestion[];
}

export interface Flashcard {
  front: string;
  back: string;
}

export interface FlashcardDeck {
  title: string;
  cards: Flashcard[];
}

export interface GraphFunction {
  expr: string;
  label: string;
  color?: string;
}

export interface GraphPoint {
  x: number;
  y: number;
  label?: string;
}

export interface GraphSpec {
  title: string;
  functions: GraphFunction[];
  points: GraphPoint[];
  xMin: number;
  xMax: number;
  yMin?: number;
  yMax?: number;
  explanation: string;
}

export interface FlowNode {
  id: string;
  label: string;
  shape: 'start' | 'end' | 'process' | 'decision' | 'io';
}

export interface FlowEdge {
  from: string;
  to: string;
  label?: string;
}

export interface MindNode {
  label: string;
  children: MindNode[];
}

export interface VennRegion {
  /** Indexes into `sets` that this region belongs to, e.g. [0, 1] for the overlap of A and B. */
  sets: number[];
  items: string[];
}

export type DiagramSpec =
  | { type: 'flowchart'; title: string; nodes: FlowNode[]; edges: FlowEdge[]; caption: string }
  | { type: 'mindmap'; title: string; root: MindNode; caption: string }
  | { type: 'venn'; title: string; sets: string[]; regions: VennRegion[]; caption: string }
  | { type: 'svg'; kind: DiagramKind; title: string; svg: string; caption: string };

export interface VideoScene {
  heading: string;
  /** Markdown + LaTeX shown on screen. */
  body: string;
  /** Plain text spoken by text-to-speech. */
  narration: string;
}

export interface VideoLesson {
  title: string;
  scenes: VideoScene[];
}

export type Artifact =
  | { kind: 'practice-question'; data: PracticeQuestion }
  | { kind: 'practice-test'; data: PracticeTest; lastScore?: { correct: number; total: number; at: number } }
  | { kind: 'flashcards'; data: FlashcardDeck }
  | { kind: 'graph'; data: GraphSpec }
  | { kind: 'diagram'; data: DiagramSpec }
  | { kind: 'video'; data: VideoLesson };

/* ---------- Lecture notes ---------- */

export type NoteStatus = 'transcribing' | 'generating' | 'done' | 'error';

export interface LectureNote {
  id: string;
  title: string;
  createdAt: number;
  durationSec?: number;
  source: 'recording' | 'upload';
  fileName?: string;
  transcript: string;
  notes: string;
  status: NoteStatus;
  error?: string;
  usage?: UsageByModel;
}
