/** Character tables shared by the TeX normalizer, the plain-text detector and the Unicode renderer. */

const SUP_PAIRS =
  '0⁰ 1¹ 2² 3³ 4⁴ 5⁵ 6⁶ 7⁷ 8⁸ 9⁹ +⁺ -⁻ =⁼ (⁽ )⁾ aᵃ bᵇ cᶜ dᵈ eᵉ fᶠ gᵍ hʰ iⁱ jʲ kᵏ lˡ mᵐ nⁿ oᵒ pᵖ rʳ sˢ tᵗ uᵘ vᵛ wʷ xˣ yʸ zᶻ ' +
  'Aᴬ Bᴮ Dᴰ Eᴱ Gᴳ Hᴴ Iᴵ Jᴶ Kᴷ Lᴸ Mᴹ Nᴺ Oᴼ Pᴾ Rᴿ Tᵀ Uᵁ Vⱽ Wᵂ';
const SUB_PAIRS = '0₀ 1₁ 2₂ 3₃ 4₄ 5₅ 6₆ 7₇ 8₈ 9₉ +₊ -₋ =₌ (₍ )₎ aₐ eₑ hₕ iᵢ jⱼ kₖ lₗ mₘ nₙ oₒ pₚ rᵣ sₛ tₜ uᵤ vᵥ xₓ';

function pairs(spec: string): [Record<string, string>, Record<string, string>] {
  const to: Record<string, string> = {};
  const from: Record<string, string> = {};
  for (const pair of spec.split(' ')) {
    const [plain, styled] = [...pair];
    to[plain] = styled;
    from[styled] = plain;
  }
  return [to, from];
}

export const [SUPERSCRIPT, FROM_SUPERSCRIPT] = pairs(SUP_PAIRS);
export const [SUBSCRIPT, FROM_SUBSCRIPT] = pairs(SUB_PAIRS);
SUPERSCRIPT['−'] = '⁻';
SUBSCRIPT['−'] = '₋';

/** Maps every character, or returns null if any has no super/subscript form. */
export function toScript(text: string, table: Record<string, string>): string | null {
  let out = '';
  for (const ch of text) {
    if (ch === ' ') continue;
    const mapped = table[ch];
    if (!mapped) return null;
    out += mapped;
  }
  return out || null;
}

export const VULGAR_FRACTIONS: Record<string, string> = {
  '1/2': '½',
  '1/3': '⅓',
  '2/3': '⅔',
  '1/4': '¼',
  '3/4': '¾',
  '1/5': '⅕',
  '2/5': '⅖',
  '3/5': '⅗',
  '4/5': '⅘',
  '1/6': '⅙',
  '5/6': '⅚',
  '1/7': '⅐',
  '1/8': '⅛',
  '3/8': '⅜',
  '5/8': '⅝',
  '7/8': '⅞',
  '1/9': '⅑',
  '1/10': '⅒',
};
export const FROM_VULGAR: Record<string, [string, string]> = Object.fromEntries(
  Object.entries(VULGAR_FRACTIONS).map(([k, v]) => [v, k.split('/') as [string, string]]),
);

/** TeX Greek command name → Unicode letter. */
export const GREEK: Record<string, string> = {
  alpha: 'α',
  beta: 'β',
  gamma: 'γ',
  delta: 'δ',
  epsilon: 'ϵ',
  varepsilon: 'ε',
  zeta: 'ζ',
  eta: 'η',
  theta: 'θ',
  vartheta: 'ϑ',
  iota: 'ι',
  kappa: 'κ',
  lambda: 'λ',
  mu: 'μ',
  nu: 'ν',
  xi: 'ξ',
  pi: 'π',
  varpi: 'ϖ',
  rho: 'ρ',
  varrho: 'ϱ',
  sigma: 'σ',
  varsigma: 'ς',
  tau: 'τ',
  upsilon: 'υ',
  phi: 'ϕ',
  varphi: 'φ',
  chi: 'χ',
  psi: 'ψ',
  omega: 'ω',
  Gamma: 'Γ',
  Delta: 'Δ',
  Theta: 'Θ',
  Lambda: 'Λ',
  Xi: 'Ξ',
  Pi: 'Π',
  Sigma: 'Σ',
  Upsilon: 'Υ',
  Phi: 'Φ',
  Psi: 'Ψ',
  Omega: 'Ω',
};

/** Unicode math characters → TeX, for model or student text that uses look-alikes. */
export const UNICODE_TO_TEX: Record<string, string> = {
  ...Object.fromEntries(Object.entries(GREEK).map(([name, ch]) => [ch, `\\${name}`])),
  ε: '\\varepsilon',
  φ: '\\varphi',
  µ: '\\mu',
  '∆': '\\Delta',
  '\u2126': '\\Omega', // ohm sign
  '×': '\\times',
  '÷': '\\div',
  '·': '\\cdot',
  '⋅': '\\cdot',
  '∙': '\\cdot',
  '±': '\\pm',
  '∓': '\\mp',
  '≤': '\\le',
  '⩽': '\\le',
  '≥': '\\ge',
  '⩾': '\\ge',
  '≠': '\\ne',
  '≈': '\\approx',
  '≅': '\\cong',
  '≡': '\\equiv',
  '∼': '\\sim',
  '∝': '\\propto',
  '∞': '\\infty',
  '→': '\\to',
  '⟶': '\\longrightarrow',
  '←': '\\leftarrow',
  '↔': '\\leftrightarrow',
  '⇒': '\\Rightarrow',
  '⟹': '\\implies',
  '⇐': '\\Leftarrow',
  '⇔': '\\Leftrightarrow',
  '⟺': '\\iff',
  '⇌': '\\rightleftharpoons',
  '∈': '\\in',
  '∉': '\\notin',
  '⊂': '\\subset',
  '⊆': '\\subseteq',
  '⊃': '\\supset',
  '⊇': '\\supseteq',
  '∪': '\\cup',
  '∩': '\\cap',
  '∅': '\\emptyset',
  '∀': '\\forall',
  '∃': '\\exists',
  '∑': '\\sum',
  '∏': '\\prod',
  '∫': '\\int',
  '∬': '\\iint',
  '∮': '\\oint',
  '∂': '\\partial',
  '∇': '\\nabla',
  '∠': '\\angle',
  '△': '\\triangle',
  '⊥': '\\perp',
  '∥': '\\parallel',
  '∘': '\\circ',
  '…': '\\ldots',
  '⋯': '\\cdots',
  ℓ: '\\ell',
  ℏ: '\\hbar',
  '∴': '\\therefore',
  '∵': '\\because',
  ℝ: '\\mathbb{R}',
  ℕ: '\\mathbb{N}',
  ℤ: '\\mathbb{Z}',
  ℚ: '\\mathbb{Q}',
  ℂ: '\\mathbb{C}',
  '−': '-',
  '–': '-',
  '′': "'",
  '″': "''",
  '°': '^{\\circ}',
};

/** TeX command name → Unicode, for places that can't run KaTeX (native text, SVG labels). */
export const TEX_SYMBOLS: Record<string, string> = {
  ...GREEK,
  times: '×',
  cdot: '·',
  cdotp: '·',
  div: '÷',
  pm: '±',
  mp: '∓',
  le: '≤',
  leq: '≤',
  leqslant: '⩽',
  ge: '≥',
  geq: '≥',
  geqslant: '⩾',
  ne: '≠',
  neq: '≠',
  approx: '≈',
  cong: '≅',
  equiv: '≡',
  sim: '∼',
  simeq: '≃',
  propto: '∝',
  infty: '∞',
  to: '→',
  rightarrow: '→',
  longrightarrow: '⟶',
  leftarrow: '←',
  gets: '←',
  leftrightarrow: '↔',
  Rightarrow: '⇒',
  Leftarrow: '⇐',
  Leftrightarrow: '⇔',
  implies: '⟹',
  iff: '⟺',
  mapsto: '↦',
  rightleftharpoons: '⇌',
  uparrow: '↑',
  downarrow: '↓',
  in: '∈',
  notin: '∉',
  ni: '∋',
  subset: '⊂',
  subseteq: '⊆',
  supset: '⊃',
  supseteq: '⊇',
  cup: '∪',
  cap: '∩',
  setminus: '∖',
  emptyset: '∅',
  varnothing: '∅',
  forall: '∀',
  exists: '∃',
  neg: '¬',
  lnot: '¬',
  land: '∧',
  wedge: '∧',
  lor: '∨',
  vee: '∨',
  sum: '∑',
  prod: '∏',
  int: '∫',
  iint: '∬',
  iiint: '∭',
  oint: '∮',
  partial: '∂',
  nabla: '∇',
  angle: '∠',
  measuredangle: '∡',
  triangle: '△',
  perp: '⊥',
  parallel: '∥',
  circ: '∘',
  bullet: '•',
  ast: '∗',
  star: '⋆',
  ldots: '…',
  dots: '…',
  cdots: '⋯',
  vdots: '⋮',
  ddots: '⋱',
  prime: '′',
  ell: 'ℓ',
  hbar: 'ℏ',
  Re: 'ℜ',
  Im: 'ℑ',
  aleph: 'ℵ',
  therefore: '∴',
  because: '∵',
  oplus: '⊕',
  otimes: '⊗',
  odot: '⊙',
  langle: '⟨',
  rangle: '⟩',
  lfloor: '⌊',
  rfloor: '⌋',
  lceil: '⌈',
  rceil: '⌉',
  vert: '|',
  lvert: '|',
  rvert: '|',
  mid: '∣',
  Vert: '‖',
  lVert: '‖',
  rVert: '‖',
  ll: '≪',
  gg: '≫',
  degree: '°',
  square: '□',
  checkmark: '✓',
  dagger: '†',
  lt: '<',
  gt: '>',
  colon: ':',
  quad: '  ',
  qquad: '   ',
  enspace: ' ',
  thinspace: ' ',
  medspace: ' ',
  thickspace: ' ',
};

/** Function names KaTeX knows as commands (\sin …). */
export const TEX_FUNCTIONS = new Set(
  'sin cos tan sec csc cot arcsin arccos arctan sinh cosh tanh coth log ln lg exp lim max min det gcd deg dim ker arg sup inf Pr hom'.split(
    ' ',
  ),
);
/** Function names that need \operatorname. */
export const OPERATOR_NAMES = new Set('lcm sgn arcsec arccsc arccot erf'.split(' '));
